### ISSUE TITLE
Rack crash when closing MIDIOverAudio module

### ISSUE THREAD

**Issue by cschol** [Ahornberg/Ahornberg-VCV-Modules#13] opened 2021-02-07 20:54 UTC
Rack crashes when `MIDIOverAudio` module is enabled and Rack is closed.

If this is the "annoying message" that the module is warning about in its dialog, then I would consider this not acceptable.

Whatever the module is doing is causing Rack to crash. We need to figure out why this happens and find a solution.

This is the stacktrace:

```
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fc4bdb5df00 (LWP 3563447))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fc4be991859 in __GI_abort () at abort.c:79
#2  0x0000562d7f38a397 in fatalSignalHandler(int) (sig=<optimized out>) at src/main.cpp:52
#3  0x00007fc4be9b2210 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000562d7f3ea299 in rack::midi::destroy() () at src/midi.cpp:278
#5  0x0000562d7f38fc15 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:225
```

**Comment by stoermelder** [comment] 2021-02-07 20:59
The cause of this issue has been reported some time ago and waits to be resolved in Rack v2:
https://github.com/VCVRack/Rack/issues/1735

**Comment by Ahornberg** [comment] 2021-02-07 21:52
Because Rack crashes on close reason, the module MIDIOverAudio is disabled by default to avoid this crash. The user can enable the module and it is also possible to disable the module again.

If it is not acceptable to include this module into the official library, I will remove it and wait until Rack v2.

**Closed** 2021-02-17 14:16 UTC
